name: Gemerate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: jackomo007/podcast-generator@main
      
